{% set version = "1.0.0" %}

package:
    name: misomip1analysis
    version: {{ version }}

source:
    path: ..

build:
    number: 1
    script: {{ PYTHON }} -m pip install . --no-deps -vv
    noarch: python
    entry_points:
        - misomip1analysis = misomip1analysis.__main__:main

requirements:
    host:
        - python
        - pip
    run:
        - python
        - numpy
        - scipy
        - matplotlib
        - netcdf4
        - xarray
        - dask
        - progressbar2
        - ffmpeg
        - cmocean

test:
    imports:
        - misomip1analysis
    commands:
        - misomip1analysis --version

about:
    home:  http://gitub.com/xylar/misomip1analysis
    license: MIT
    license_file: LICENSE
    summary: A python package for analyzing MISOMIP1 and ISOMIP+ simulation results

extra:
    recipe-maintainers:
        - xylar
